```python

# A lookup dictionary which, given a letter will return the morse code equivalent
_letter_to_morse = {'a':'.-', 'b':'-...', 'c':'-.-.', 'd':'-..', 'e':'.', 'f':'..-.', 
                   'g':'--.', 'h':'....', 'i':'..', 'j':'.---', 'k':'-.-', 'l':'.-..', 'm':'--', 
                   'n':'-.', 'o':'---', 'p':'.--.', 'q':'--.-', 'r':'.-.', 's':'...', 't':'-',
                   'u':'..-', 'v':'...-', 'w':'.--', 'x':'-..-', 'y':'-.--', 'z':'--..',
                   '0':'-----', '1':'.----', '2':'..---', '3':'...--', '4':'....-',
                   '5':'.....', '6':'-....', '7':'--...', '8':'---..', '9':'----.',
                   ' ':'/'}

# This will create a dictionary that can go from the morse back to the letter
_morse_to_letter = {}
for letter in _letter_to_morse:
    morse = _letter_to_morse[letter]
    _morse_to_letter[morse] = letter


def encode(message):
    """
    Encode a message from English to Morse Code
    
    Args:
        message (str): the English message to encode
    
    Returns:
        str: The encoded message
    
    Examples:
        >>> encode("Help us")
        '.... . .-.. .--. / ..- ...'
    """
    morse = []

    for letter in message:
        letter = letter.lower()
        
        if letter not in _letter_to_morse:
            raise ValueError(f"Cannot encode \"{message}\". Character \"{letter}\" not in Morse dictionary")
        
        morse.append(_letter_to_morse[letter])

    # We need to join together Morse code letters with spaces
    morse_message = " ".join(morse)
    
    return morse_message


def decode(message):
    """
    Decode a message from Morse Code to English
    
    Args:
        message (str): the Morse Code message to decode
    
    Returns:
        str: The decoded English message
    
    Examples:
        >>> decode(".... . .-.. .--. / ..- ...")
        'help us'
    """
    english = []

    # Now we cannot read by letter. We know that morse letters are
    # separated by a space, so we split the morse string by spaces
    morse_letters = message.split(" ")

    for letter in morse_letters:
        english.append(_morse_to_letter[letter])

    # Rejoin, but now we don't need to add any spaces
    english_message = "".join(english)
    
    return english_message
```




```python

import pytest

from morse import encode, decode

@pytest.mark.parametrize("message, output", [
    ("SOS", "... --- ..."),
    ("help", ".... . .-.. .--."),
    ("", ""),
    (" ", "/"),
])
def test_encode(message, output):
    assert encode(message) == output

@pytest.mark.parametrize("message, output", [
    ("... --- ...", "sos"),
    (".... . .-.. .--.", "help"),
    ("/", " "),
])
def test_decode(message, output):
    assert decode(message) == output

def test_error():  # New test
    with pytest.raises(ValueError):
        encode("Don't forget to save us")

@pytest.mark.parametrize("message", [
    "It's sinking",
    "Titanic & Olympic",
    "This boat is expensive £££",
    "Help!",
])
def test_errors(message):  # New test
    with pytest.raises(ValueError):
        encode(message)
```

    Overwriting test_morse.py



```python
pytest -v --doctest-modules morse.py test_morse.py
```

    [1m=================== test session starts ====================[0m
    platform linux -- Python 3.8.5, pytest-6.0.2, py-1.9.0, pluggy-0.13.1 -- /home/matt/projects/courses/software_engineering_best_practices/venv/bin/python3
    cachedir: .pytest_cache
    rootdir: /home/matt/projects/courses/software_engineering_best_practices
    plugins: nbval-0.9.6
    collected 14 items                                         [0m
    
    morse.py::morse.decode [32mPASSED[0m[32m                        [  7%][0m
    morse.py::morse.encode [32mPASSED[0m[32m                        [ 14%][0m
    test_morse.py::test_encode[SOS-... --- ...] [32mPASSED[0m[32m   [ 21%][0m
    test_morse.py::test_encode[help-.... . .-.. .--.] [32mPASSED[0m[32m [ 28%][0m
    test_morse.py::test_encode[-] [32mPASSED[0m[32m                 [ 35%][0m
    test_morse.py::test_encode[ -/] [32mPASSED[0m[32m               [ 42%][0m
    test_morse.py::test_decode[... --- ...-sos] [32mPASSED[0m[32m   [ 50%][0m
    test_morse.py::test_decode[.... . .-.. .--.-help] [32mPASSED[0m[32m [ 57%][0m
    test_morse.py::test_decode[/- ] [32mPASSED[0m[32m               [ 64%][0m
    test_morse.py::test_error [32mPASSED[0m[32m                     [ 71%][0m
    test_morse.py::test_errors[It's sinking] [32mPASSED[0m[32m      [ 78%][0m
    test_morse.py::test_errors[Titanic & Olympic] [32mPASSED[0m[32m [ 85%][0m
    test_morse.py::test_errors[This boat is expensive \xa3\xa3\xa3] [32mPASSED[0m[32m [ 92%][0m
    test_morse.py::test_errors[Help!] [32mPASSED[0m[32m             [100%][0m
    
    [32m==================== [32m[1m14 passed[0m[32m in 0.03s[0m[32m ====================[0m

